// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoNvKzpb5EXoE6vJgpfxv5epwOZDrZEwg',
    appId: '1:427540188324:web:822edbb12b954dea9c2a31',
    messagingSenderId: '427540188324',
    projectId: 'amanah-app-56130',
    authDomain: 'amanah-app-56130.firebaseapp.com',
    storageBucket: 'amanah-app-56130.appspot.com',
    measurementId: 'G-PJP59YFT7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtKHAVcDddON3U5o5kR_knyGludftnhdg',
    appId: '1:427540188324:android:e38fa9c5d52afe7b9c2a31',
    messagingSenderId: '427540188324',
    projectId: 'amanah-app-56130',
    storageBucket: 'amanah-app-56130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Mib6WdBtfVrahjzAvltuhNb3hvoTitY',
    appId: '1:427540188324:ios:e8f3e47af22377329c2a31',
    messagingSenderId: '427540188324',
    projectId: 'amanah-app-56130',
    storageBucket: 'amanah-app-56130.appspot.com',
    iosBundleId: 'com.example.amanah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Mib6WdBtfVrahjzAvltuhNb3hvoTitY',
    appId: '1:427540188324:ios:e8f3e47af22377329c2a31',
    messagingSenderId: '427540188324',
    projectId: 'amanah-app-56130',
    storageBucket: 'amanah-app-56130.appspot.com',
    iosBundleId: 'com.example.amanah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoNvKzpb5EXoE6vJgpfxv5epwOZDrZEwg',
    appId: '1:427540188324:web:2a0c0a8ddc4ea24b9c2a31',
    messagingSenderId: '427540188324',
    projectId: 'amanah-app-56130',
    authDomain: 'amanah-app-56130.firebaseapp.com',
    storageBucket: 'amanah-app-56130.appspot.com',
    measurementId: 'G-7F6P8R3Q6K',
  );
}
